stages:
  - build
  - deploy

pages:
  stage: build
  script:
    - mkdir .public
    - cp -r $CI_PROJECT_DIR/* .public
    - ls -ltr .public
    - mv .public public
  artifacts:
    paths:
      - public

dfsdeploy:
  stage: deploy
  only:
    - r125
  image: gitlab-registry.cern.ch/ci-tools/ci-web-deployer:latest
  script:
    - deploy-dfs
